### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ServerProxy'

### ISSUE THREAD

**Issue by SeekPoint** [seominjoon/dqa-net#2]
mldl@mldlUB1604:~/ub16_prj/dqa-net$ python -m prepro.p05
dumping json files ... 
done
N/A%|                                                                                                                                                                                        |ETA:  --:--:--Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mldl/ub16_prj/dqa-net/prepro/p05.py", line 493, in <module>
    prepro_questions(ARGS)
  File "/home/mldl/ub16_prj/dqa-net/prepro/p05.py", line 323, in prepro_questions
    sents = [_tokenize(qa2hypo(ques_text, choice, args.qa2hypo, args.qa2hypo_path)) for choice in d['answerTexts']]
  File "/home/mldl/ub16_prj/dqa-net/prepro/p05.py", line 37, in qa2hypo
    from qa2hypo import qa2hypo as f
  File "qa2hypo/qa2hypo.py", line 7, in <module>
    from helper import *
  File "qa2hypo/helper.py", line 1, in <module>
    from parser import *
  File "qa2hypo/parser.py", line 10, in <module>
    server = jsonrpc.ServerProxy(jsonrpc.JsonRpc20(), jsonrpc.TransportTcpIp(addr=("127.0.0.1", 8080)))
AttributeError: 'module' object has no attribute 'ServerProxy'
mldl@mldlUB1604:~/ub16_prj/dqa-net$

**Comment by ghost** [comment]
you need to use jsonrpc that comes with stanford-corenlp-python
